--PERSON -- 
INSERT INTO Person (name,phoneNumber,address,nif,birthdate,personType) VALUES ('Alisa','922759286','1047 Sapien. St.','700071599','23/06/2016','Teacher');
INSERT INTO Person (name,phoneNumber,address,nif,birthdate,personType) VALUES ('Anjolie','932615276','P.O. Box 370, 765 Aliquam St.','043101353','23/10/2015','Teacher');
INSERT INTO Person (name,phoneNumber,address,nif,birthdate,personType) VALUES ('Clio','969239410','5375 Sed, Road','664833255','13/07/2016','Teacher');
INSERT INTO Person (name,phoneNumber,address,nif,birthdate,personType) VALUES ('Nomlanga','936843091','815-3768 Et, Road','774444665','30/07/2016','Teacher');
INSERT INTO Person (name,phoneNumber,address,nif,birthdate,personType) VALUES ('Riley','977798250','119-5635 Malesuada Road','491589491','29/10/2016','Teacher');
INSERT INTO Person (name,phoneNumber,address,nif,birthdate,personType) VALUES ('Sophia','991561940','Ap #884-7926 Luctus St.','726885360','04/07/2016','Teacher');
INSERT INTO Person (name,phoneNumber,address,nif,birthdate,personType) VALUES ('Britanni','986362234','641-2551 Lectus. Road','694874523','28/07/2016','Teacher');
INSERT INTO Person (name,phoneNumber,address,nif,birthdate,personType) VALUES ('Kiayada','920757398','P.O. Box 541, 942 Cubilia Ave','138488825','20/04/2015','Teacher');
INSERT INTO Person (name,phoneNumber,address,nif,birthdate,personType) VALUES ('Madaline','901727919','P.O. Box 844, 8140 Etiam Rd.','483353954','13/12/2015','Teacher');
INSERT INTO Person (name,phoneNumber,address,nif,birthdate,personType) VALUES ('Tashya','998061785','635-7047 Augue Ave','372329297','02/05/2015','Teacher');
INSERT INTO Person (name,phoneNumber,address,nif,birthdate,personType) VALUES ('Isabella','921341979','P.O. Box 655, 8047 Eu Street','009710097','10/09/2016','Student');
INSERT INTO Person (name,phoneNumber,address,nif,birthdate,personType) VALUES ('Herman','921219039','P.O. Box 687, 8043 Nibh Av.','775829991','21/09/2015','Student');
INSERT INTO Person (name,phoneNumber,address,nif,birthdate,personType) VALUES ('Jaquelyn','995124683','Ap #987-1820 Augue. St.','201720821','22/08/2015','Student');
INSERT INTO Person (name,phoneNumber,address,nif,birthdate,personType) VALUES ('Danielle','909022509','P.O. Box 401, 4025 Consequat Av.','741424904','17/05/2016','Student');
INSERT INTO Person (name,phoneNumber,address,nif,birthdate,personType) VALUES ('Martin','985432632','7875 Tincidunt Road','016155243','01/03/2017','Student');
INSERT INTO Person (name,phoneNumber,address,nif,birthdate,personType) VALUES ('Isabelle','986852240','2252 Sed St.','807677902','13/10/2015','Student');
INSERT INTO Person (name,phoneNumber,address,nif,birthdate,personType) VALUES ('Mohammad','931204608','964-9622 Sed, St.','208327074','30/10/2016','Student');
INSERT INTO Person (name,phoneNumber,address,nif,birthdate,personType) VALUES ('Carlos','951669087','Ap #840-9157 Semper Ave','575201362','29/10/2015','Student');
INSERT INTO Person (name,phoneNumber,address,nif,birthdate,personType) VALUES ('Nomlanga','970680244','2982 Natoque Rd.','498486217','13/12/2015','Student');
INSERT INTO Person (name,phoneNumber,address,nif,birthdate,personType) VALUES ('Michael','908028952','P.O. Box 184, 7228 Suspendisse Avenue','159509519','10/07/2015','Student');
INSERT INTO Person (name,phoneNumber,address,nif,birthdate,personType) VALUES ('Vanna','902581515','3231 Sociis Street','309310507','13/02/2016','Teacher');
INSERT INTO Person (name,phoneNumber,address,nif,birthdate,personType) VALUES ('Sybil','938668897','9941 Montes, Street','882693400','27/09/2015','Teacher');
INSERT INTO Person (name,phoneNumber,address,nif,birthdate,personType) VALUES ('Ori','900436053','Ap #982-4315 Eget, Road','170400081','18/12/2016','Teacher');
INSERT INTO Person (name,phoneNumber,address,nif,birthdate,personType) VALUES ('Eliana','919737329','Ap #883-1620 Nec Rd.','498876276','07/07/2016','Teacher');
INSERT INTO Person (name,phoneNumber,address,nif,birthdate,personType) VALUES ('Yuri','921059718','615-1328 Arcu. Ave','879521772','06/07/2016','Teacher');
INSERT INTO Person (name,phoneNumber,address,nif,birthdate,personType) VALUES ('Angela','930207314','738-2137 Augue Av.','054416863','08/04/2016','Teacher');
INSERT INTO Person (name,phoneNumber,address,nif,birthdate,personType) VALUES ('Wynter','981191672','818-7210 Mollis Avenue','883799807','14/01/2017','Teacher');
INSERT INTO Person (name,phoneNumber,address,nif,birthdate,personType) VALUES ('Quyn','947734240','Ap #140-1544 Cursus Ave','925827845','07/01/2016','Teacher');
INSERT INTO Person (name,phoneNumber,address,nif,birthdate,personType) VALUES ('Gregory','958266794','6404 In, Street','232648994','30/04/2015','Teacher');
INSERT INTO Person (name,phoneNumber,address,nif,birthdate,personType) VALUES ('Leila','934366381','664-9246 Sed Avenue','991614815','08/06/2016','Teacher');
INSERT INTO Person (name,phoneNumber,address,nif,birthdate,personType) VALUES ('Ruth','938351263','9803 Mollis Ave','883310415','25/04/2015','Student');
INSERT INTO Person (name,phoneNumber,address,nif,birthdate,personType) VALUES ('Edan','920940785','8429 Auctor, Avenue','816752936','31/03/2017','Student');
INSERT INTO Person (name,phoneNumber,address,nif,birthdate,personType) VALUES ('Cathleen','924405510','Ap #122-9591 Elementum, St.','773519511','28/02/2016','Student');
INSERT INTO Person (name,phoneNumber,address,nif,birthdate,personType) VALUES ('Marcia','990175676','1761 A, St.','028525453','01/01/2016','Student');
INSERT INTO Person (name,phoneNumber,address,nif,birthdate,personType) VALUES ('Yetta','978777976','P.O. Box 583, 3174 Sapien, Road','729862055','07/01/2017','Student');
INSERT INTO Person (name,phoneNumber,address,nif,birthdate,personType) VALUES ('Carolyn','984403487','100-9386 A Rd.','685977634','14/07/2016','Student');
INSERT INTO Person (name,phoneNumber,address,nif,birthdate,personType) VALUES ('Azalia','901520496','P.O. Box 613, 7693 Arcu. St.','115301702','25/01/2016','Student');
INSERT INTO Person (name,phoneNumber,address,nif,birthdate,personType) VALUES ('Kameko','952226915','Ap #900-550 Vestibulum St.','851377981','23/10/2015','Student');
INSERT INTO Person (name,phoneNumber,address,nif,birthdate,personType) VALUES ('Macaulay','974132570','P.O. Box 129, 3349 Rhoncus Av.','525427017','18/12/2015','Student');
INSERT INTO Person (name,phoneNumber,address,nif,birthdate,personType) VALUES ('Levi','921131320','P.O. Box 107, 9161 Eget, Avenue','458663091','20/11/2016','Student');
INSERT INTO Person (name,phoneNumber,address,nif,birthdate,personType) VALUES ('Zachary','997941064','455-338 Eu, St.','497150755','23/11/2015','Teacher');
INSERT INTO Person (name,phoneNumber,address,nif,birthdate,personType) VALUES ('Macy','999748735','3361 Lorem, Street','690114289','21/05/2015','Teacher');
INSERT INTO Person (name,phoneNumber,address,nif,birthdate,personType) VALUES ('Brody','985699523','166-9881 At, St.','928241356','03/09/2016','Teacher');
INSERT INTO Person (name,phoneNumber,address,nif,birthdate,personType) VALUES ('Joseph','955686244','9278 Duis Ave','833555079','10/07/2015','Teacher');
INSERT INTO Person (name,phoneNumber,address,nif,birthdate,personType) VALUES ('Grant','996398030','805-1116 Arcu. Street','213421273','11/05/2016','Teacher');
INSERT INTO Person (name,phoneNumber,address,nif,birthdate,personType) VALUES ('Marshall','974214789','P.O. Box 934, 7754 Sociis Ave','422561159','19/01/2016','Teacher');
INSERT INTO Person (name,phoneNumber,address,nif,birthdate,personType) VALUES ('Rana','974847487','P.O. Box 708, 1646 Malesuada Av.','569434626','09/09/2016','Teacher');
INSERT INTO Person (name,phoneNumber,address,nif,birthdate,personType) VALUES ('Melissa','920629324','P.O. Box 915, 6463 Erat St.','115200257','17/01/2017','Teacher');
INSERT INTO Person (name,phoneNumber,address,nif,birthdate,personType) VALUES ('Maite','935179203','Ap #261-4990 Amet St.','904666730','06/04/2016','Teacher');
INSERT INTO Person (name,phoneNumber,address,nif,birthdate,personType) VALUES ('Malik','907673450','540-4899 Mauris St.','097548987','20/05/2016','Teacher');
INSERT INTO Person (name,phoneNumber,address,nif,birthdate,personType) VALUES ('Bertha','992644861','4136 Suscipit Ave','912283960','05/05/2015','Student');
INSERT INTO Person (name,phoneNumber,address,nif,birthdate,personType) VALUES ('Aquila','953958561','4176 Risus. St.','835282172','01/11/2016','Student');
INSERT INTO Person (name,phoneNumber,address,nif,birthdate,personType) VALUES ('Josiah','909625897','P.O. Box 712, 1264 In St.','167685184','24/12/2015','Student');
INSERT INTO Person (name,phoneNumber,address,nif,birthdate,personType) VALUES ('Hall','998821885','Ap #137-2290 Urna, Rd.','078420966','29/08/2015','Student');
INSERT INTO Person (name,phoneNumber,address,nif,birthdate,personType) VALUES ('Brady','970210049','273-5814 Gravida Street','238172183','22/03/2017','Student');
INSERT INTO Person (name,phoneNumber,address,nif,birthdate,personType) VALUES ('Orli','996066286','Ap #827-6770 A St.','011755663','14/09/2016','Student');
INSERT INTO Person (name,phoneNumber,address,nif,birthdate,personType) VALUES ('Brenden','959959410','7929 Rhoncus. Avenue','662612245','09/05/2015','Student');
INSERT INTO Person (name,phoneNumber,address,nif,birthdate,personType) VALUES ('Ishmael','996000331','918-1381 Rutrum St.','409244793','24/06/2015','Student');
INSERT INTO Person (name,phoneNumber,address,nif,birthdate,personType) VALUES ('Bert','992849447','P.O. Box 468, 624 Aliquam Ave','655052469','14/01/2017','Student');
INSERT INTO Person (name,phoneNumber,address,nif,birthdate,personType) VALUES ('Alan','913724896','8857 Eu, Street','163950542','20/08/2016','Student');
INSERT INTO Person (name,phoneNumber,address,nif,birthdate,personType) VALUES ('Tara','991097369','P.O. Box 311, 3795 Nec St.','235907320','20/06/2016','Teacher');
INSERT INTO Person (name,phoneNumber,address,nif,birthdate,personType) VALUES ('Upton','909916277','855-5695 Et St.','633186118','05/04/2017','Teacher');
INSERT INTO Person (name,phoneNumber,address,nif,birthdate,personType) VALUES ('Jakeem','928030877','P.O. Box 855, 1637 Eget, Street','494872247','24/11/2016','Teacher');
INSERT INTO Person (name,phoneNumber,address,nif,birthdate,personType) VALUES ('Hedwig','993212354','865-1624 Magnis St.','676699128','22/05/2015','Teacher');
INSERT INTO Person (name,phoneNumber,address,nif,birthdate,personType) VALUES ('Troy','968523449','P.O. Box 724, 4179 Sem, Rd.','960713783','04/09/2016','Teacher');
INSERT INTO Person (name,phoneNumber,address,nif,birthdate,personType) VALUES ('Nathan','956536132','Ap #577-3396 Praesent St.','312551650','10/01/2017','Teacher');
INSERT INTO Person (name,phoneNumber,address,nif,birthdate,personType) VALUES ('Veda','931158119','598-7198 Aliquam St.','188925031','20/02/2016','Teacher');
INSERT INTO Person (name,phoneNumber,address,nif,birthdate,personType) VALUES ('Phyllis','971210611','643-1887 Mi St.','874136610','17/12/2015','Teacher');
INSERT INTO Person (name,phoneNumber,address,nif,birthdate,personType) VALUES ('Moses','998804848','2985 Pellentesque Avenue','369983143','30/07/2016','Teacher');
INSERT INTO Person (name,phoneNumber,address,nif,birthdate,personType) VALUES ('Kadeem','986588000','3370 Ridiculus St.','631685686','11/01/2017','Teacher');
INSERT INTO Person (name,phoneNumber,address,nif,birthdate,personType) VALUES ('Bree','992021291','P.O. Box 466, 3913 Arcu. Street','504690543','28/07/2015','Student');
INSERT INTO Person (name,phoneNumber,address,nif,birthdate,personType) VALUES ('Kato','946258575','932-9289 Sed, Avenue','476097174','31/07/2016','Student');
INSERT INTO Person (name,phoneNumber,address,nif,birthdate,personType) VALUES ('Roanna','932399887','2917 Integer Ave','717739110','21/06/2016','Student');
INSERT INTO Person (name,phoneNumber,address,nif,birthdate,personType) VALUES ('Elizabeth','950650213','Ap #648-9116 Purus. St.','399172599','28/03/2016','Student');
INSERT INTO Person (name,phoneNumber,address,nif,birthdate,personType) VALUES ('Pearl','910854880','9063 Convallis Av.','813266782','26/10/2015','Student');
INSERT INTO Person (name,phoneNumber,address,nif,birthdate,personType) VALUES ('Seth','940970264','8538 Orci, Rd.','058778468','10/09/2015','Student');
INSERT INTO Person (name,phoneNumber,address,nif,birthdate,personType) VALUES ('Calvin','993400829','681-8243 Nisi Ave','497320594','09/01/2016','Student');
INSERT INTO Person (name,phoneNumber,address,nif,birthdate,personType) VALUES ('Guy','991493332','838-9700 Faucibus St.','633988777','08/01/2017','Student');
INSERT INTO Person (name,phoneNumber,address,nif,birthdate,personType) VALUES ('Rama','925139502','Ap #384-4420 Phasellus Ave','325114348','15/05/2016','Student');
INSERT INTO Person (name,phoneNumber,address,nif,birthdate,personType) VALUES ('Gregory','981621074','Ap #367-686 Mauris, Av.','340032453','02/06/2015','Student');
INSERT INTO Person (name,phoneNumber,address,nif,birthdate,personType) VALUES ('Zia','923386572','Ap #326-3139 At, Ave','875585009','05/04/2017','Teacher');
INSERT INTO Person (name,phoneNumber,address,nif,birthdate,personType) VALUES ('David','993132962','P.O. Box 347, 9640 Mauris Road','837127481','11/09/2015','Teacher');
INSERT INTO Person (name,phoneNumber,address,nif,birthdate,personType) VALUES ('Aileen','937245830','1676 Velit St.','087652793','23/12/2015','Teacher');
INSERT INTO Person (name,phoneNumber,address,nif,birthdate,personType) VALUES ('Octavia','902983898','721-2427 Ac Rd.','527810509','17/10/2015','Teacher');
INSERT INTO Person (name,phoneNumber,address,nif,birthdate,personType) VALUES ('Steven','954746383','P.O. Box 891, 4887 Gravida. Avenue','856043897','16/04/2016','Teacher');
INSERT INTO Person (name,phoneNumber,address,nif,birthdate,personType) VALUES ('Joelle','968973130','4518 Viverra. Road','292195203','15/08/2015','Teacher');
INSERT INTO Person (name,phoneNumber,address,nif,birthdate,personType) VALUES ('Chadwick','900990339','P.O. Box 892, 3392 Morbi St.','061597795','24/11/2015','Teacher');
INSERT INTO Person (name,phoneNumber,address,nif,birthdate,personType) VALUES ('Evelyn','915372703','6705 Dolor St.','623614254','16/02/2017','Teacher');
INSERT INTO Person (name,phoneNumber,address,nif,birthdate,personType) VALUES ('Jolene','971220479','8153 Nisi Avenue','853247228','21/01/2017','Teacher');
INSERT INTO Person (name,phoneNumber,address,nif,birthdate,personType) VALUES ('Kyra','986337208','P.O. Box 344, 3013 Penatibus Av.','711370597','13/06/2015','Teacher');
INSERT INTO Person (name,phoneNumber,address,nif,birthdate,personType) VALUES ('Elijah','943727884','P.O. Box 619, 8148 Auctor, Rd.','338613460','05/02/2017','Student');
INSERT INTO Person (name,phoneNumber,address,nif,birthdate,personType) VALUES ('Dexter','963545816','538-8164 A, Street','588872826','03/11/2015','Student');
INSERT INTO Person (name,phoneNumber,address,nif,birthdate,personType) VALUES ('April','944075840','Ap #309-7516 Dictum Street','154288040','22/11/2016','Student');
INSERT INTO Person (name,phoneNumber,address,nif,birthdate,personType) VALUES ('Ifeoma','955237719','4822 Sed St.','690007685','30/11/2015','Student');
INSERT INTO Person (name,phoneNumber,address,nif,birthdate,personType) VALUES ('Chadwick','992450432','Ap #215-3490 Nascetur St.','201338616','06/04/2016','Student');
INSERT INTO Person (name,phoneNumber,address,nif,birthdate,personType) VALUES ('Carson','910775072','P.O. Box 130, 4811 Enim St.','062228618','29/10/2016','Student');
INSERT INTO Person (name,phoneNumber,address,nif,birthdate,personType) VALUES ('Rachel','983731033','Ap #311-3683 Nisl. Road','348096649','19/11/2015','Student');
INSERT INTO Person (name,phoneNumber,address,nif,birthdate,personType) VALUES ('Dai','904356664','8855 Rutrum Road','869253974','20/05/2015','Student');
INSERT INTO Person (name,phoneNumber,address,nif,birthdate,personType) VALUES ('Brianna','931379386','615 Morbi Street','214467397','12/10/2016','Student');
INSERT INTO Person (name,phoneNumber,address,nif,birthdate,personType) VALUES ('Flavia','978311142','P.O. Box 594, 7211 Ultrices, St.','817732908','15/05/2015','Student');

--Course
INSERT INTO Course (directorCode,courseType,name,creationDate,currentCalendarYear,description) VALUES (15,'PhD','suscipit,','02/04/2016',2016,'aliquet vel, vulputate eu, odio. Phasellus at augue id ante dictum cursus. Nunc mauris elit, dictum eu, eleifend nec, malesuada ut, sem. Nulla interdum. Curabitur dictum. Phasellus in felis. Nulla tempor augue ac ipsum. Phasellus vitae mauris sit amet lorem semper auctor. Mauris vel turpis. Aliquam adipiscing lobortis risus. In mi pede, nonummy ut, molestie in, tempus eu, ligula. Aenean euismod mauris eu elit. Nulla facilisi. Sed neque. Sed eget lacus. Mauris non dui nec urna suscipit nonummy. Fusce fermentum fermentum arcu. Vestibulum ante ipsum primis in faucibus orci');
INSERT INTO Course (directorCode,courseType,name,creationDate,currentCalendarYear,description) VALUES (45,'PhD','MIEIC','05/12/2016',2016,'non enim commodo hendrerit. Donec porttitor tellus non magna. Nam ligula elit, pretium et, rutrum non, hendrerit id, ante. Nunc mauris sapien, cursus in, hendrerit consectetuer, cursus et, magna. Praesent interdum ligula eu enim. Etiam imperdiet dictum magna. Ut tincidunt orci quis lectus. Nullam suscipit, est ac facilisis facilisis, magna tellus faucibus leo, in');
INSERT INTO Course (directorCode,courseType,name,creationDate,currentCalendarYear,description) VALUES (89,'PhD','non','19/02/2016',2016,'dolor elit, pellentesque a, facilisis non, bibendum sed, est. Nunc laoreet lectus quis massa. Mauris vestibulum, neque sed dictum eleifend, nunc risus varius orci, in consequat enim diam vel arcu.');
INSERT INTO Course (directorCode,courseType,name,creationDate,currentCalendarYear,description) VALUES (99,'PhD','interdum.','25/10/2016',2016,'ullamcorper magna. Sed eu eros. Nam consequat dolor vitae dolor. Donec fringilla. Donec feugiat metus sit amet ante. Vivamus non lorem vitae odio sagittis semper. Nam tempor diam dictum sapien. Aenean massa. Integer vitae nibh.');
INSERT INTO Course (directorCode,courseType,name,creationDate,currentCalendarYear,description) VALUES (79,'PhD','lacus.','05/08/2015',2016,'ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec tincidunt. Donec vitae erat vel pede blandit congue. In scelerisque scelerisque dui. Suspendisse ac metus vitae velit egestas lacinia. Sed congue, elit sed consequat auctor, nunc nulla');
INSERT INTO Course (directorCode,courseType,name,creationDate,currentCalendarYear,description) VALUES (94,'PhD','elementum','08/05/2015',2016,'vitae, erat. Vivamus nisi. Mauris nulla. Integer urna. Vivamus molestie dapibus ligula. Aliquam erat volutpat. Nulla dignissim. Maecenas ornare egestas ligula. Nullam feugiat placerat velit. Quisque varius. Nam porttitor scelerisque neque. Nullam nisl. Maecenas malesuada fringilla est. Mauris');
INSERT INTO Course (directorCode,courseType,name,creationDate,currentCalendarYear,description) VALUES (63,'PhD','dis','09/09/2015',2016,'neque venenatis lacus. Etiam bibendum fermentum metus. Aenean sed pede nec ante blandit viverra. Donec tempus, lorem fringilla ornare placerat, orci lacus vestibulum lorem, sit amet ultricies sem magna nec quam. Curabitur vel lectus. Cum sociis natoque penatibus et magnis dis parturient montes,');
INSERT INTO Course (directorCode,courseType,name,creationDate,currentCalendarYear,description) VALUES (32,'PhD','molestie','13/11/2015',2016,'aliquet odio. Etiam ligula tortor, dictum eu, placerat eget, venenatis a, magna. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Etiam laoreet, libero et tristique pellentesque, tellus sem mollis');
INSERT INTO Course (directorCode,courseType,name,creationDate,currentCalendarYear,description) VALUES (61,'PhD','rhoncus.','11/11/2016',2016,'auctor odio a purus. Duis elementum, dui quis accumsan convallis, ante lectus convallis est, vitae sodales nisi magna sed dui. Fusce aliquam, enim nec tempus scelerisque, lorem ipsum sodales purus, in molestie tortor nibh sit amet orci. Ut sagittis lobortis mauris. Suspendisse aliquet molestie tellus. Aenean egestas hendrerit neque. In ornare sagittis felis. Donec tempor, est ac mattis semper, dui lectus rutrum urna, nec luctus felis purus ac');
INSERT INTO Course (directorCode,courseType,name,creationDate,currentCalendarYear,description) VALUES (95,'PhD','gravida','14/04/2015',2016,'dolor egestas rhoncus. Proin nisl sem, consequat nec, mollis vitae, posuere at, velit. Cras lorem lorem, luctus ut, pellentesque eget, dictum placerat, augue. Sed molestie. Sed id risus quis diam luctus lobortis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Mauris ut quam vel sapien imperdiet ornare. In faucibus. Morbi vehicula. Pellentesque tincidunt tempus risus. Donec egestas. Duis ac arcu. Nunc mauris. Morbi non sapien molestie orci tincidunt adipiscing. Mauris molestie pharetra nibh. Aliquam ornare, libero at auctor ullamcorper, nisl arcu iaculis enim, sit amet ornare');
INSERT INTO Course (directorCode,courseType,name,creationDate,currentCalendarYear,description) VALUES (43,'Masters','Etiam','23/02/2016',2016,'risus. Duis a mi fringilla mi lacinia mattis. Integer eu lacus. Quisque imperdiet, erat nonummy ultricies ornare, elit elit fermentum risus, at fringilla purus mauris a nunc. In at pede. Cras vulputate velit eu sem. Pellentesque ut ipsum ac mi eleifend egestas. Sed pharetra, felis eget varius ultrices, mauris ipsum porta elit, a feugiat tellus lorem eu metus. In lorem. Donec elementum, lorem ut aliquam iaculis, lacus pede sagittis augue, eu tempor erat neque non quam. Pellentesque habitant morbi tristique senectus et');
INSERT INTO Course (directorCode,courseType,name,creationDate,currentCalendarYear,description) VALUES (48,'Masters','Cras','21/12/2016',2016,'a, facilisis non, bibendum sed, est. Nunc laoreet lectus quis massa. Mauris vestibulum, neque sed dictum eleifend, nunc risus varius orci, in consequat enim diam vel arcu. Curabitur ut odio vel est tempor bibendum. Donec felis orci, adipiscing non, luctus sit amet, faucibus ut, nulla. Cras eu tellus eu augue porttitor interdum. Sed auctor odio a purus. Duis elementum,');
INSERT INTO Course (directorCode,courseType,name,creationDate,currentCalendarYear,description) VALUES (98,'Masters','risus,','31/12/2016',2016,'Donec at arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec tincidunt. Donec vitae erat vel pede blandit congue. In scelerisque scelerisque dui. Suspendisse ac metus vitae velit egestas lacinia. Sed congue, elit sed consequat auctor, nunc nulla vulputate');
INSERT INTO Course (directorCode,courseType,name,creationDate,currentCalendarYear,description) VALUES (59,'Masters','euismod','22/11/2016',2016,'Donec tincidunt. Donec vitae erat vel pede blandit congue. In scelerisque scelerisque dui. Suspendisse ac metus vitae velit egestas lacinia. Sed congue, elit sed consequat auctor, nunc nulla vulputate dui, nec tempus mauris erat eget ipsum. Suspendisse sagittis. Nullam vitae diam. Proin dolor. Nulla semper tellus id nunc interdum feugiat. Sed nec metus facilisis lorem tristique aliquet. Phasellus fermentum convallis ligula. Donec luctus aliquet odio. Etiam ligula tortor, dictum eu, placerat eget, venenatis a, magna. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Etiam laoreet, libero et tristique pellentesque, tellus sem mollis dui, in sodales');
INSERT INTO Course (directorCode,courseType,name,creationDate,currentCalendarYear,description) VALUES (61,'Masters','Aenean','07/08/2015',2016,'Donec vitae erat vel pede blandit congue. In scelerisque scelerisque dui. Suspendisse ac metus vitae velit egestas lacinia. Sed congue, elit sed consequat auctor, nunc nulla vulputate dui, nec tempus');
INSERT INTO Course (directorCode,courseType,name,creationDate,currentCalendarYear,description) VALUES (66,'Masters','eget,','13/06/2016',2016,'Maecenas mi felis, adipiscing fringilla, porttitor vulputate, posuere vulputate, lacus. Cras interdum. Nunc sollicitudin commodo ipsum. Suspendisse non leo. Vivamus nibh dolor, nonummy ac, feugiat non, lobortis quis, pede. Suspendisse dui. Fusce diam nunc, ullamcorper eu, euismod ac, fermentum vel, mauris. Integer sem elit, pharetra ut, pharetra sed, hendrerit a, arcu. Sed et libero. Proin mi. Aliquam gravida mauris ut mi. Duis risus odio, auctor vitae, aliquet nec, imperdiet nec, leo. Morbi neque tellus, imperdiet non, vestibulum nec, euismod in, dolor. Fusce feugiat. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam auctor, velit');
INSERT INTO Course (directorCode,courseType,name,creationDate,currentCalendarYear,description) VALUES (81,'Masters','commodo','27/12/2015',2016,'ante. Maecenas mi felis, adipiscing fringilla, porttitor vulputate, posuere vulputate, lacus. Cras interdum. Nunc sollicitudin commodo ipsum. Suspendisse non leo. Vivamus nibh dolor, nonummy ac, feugiat non, lobortis quis, pede. Suspendisse dui. Fusce diam nunc, ullamcorper eu, euismod ac, fermentum vel, mauris. Integer sem elit, pharetra ut, pharetra sed, hendrerit a, arcu. Sed et libero. Proin mi. Aliquam gravida mauris ut mi. Duis risus odio, auctor vitae, aliquet');
INSERT INTO Course (directorCode,courseType,name,creationDate,currentCalendarYear,description) VALUES (30,'Masters','eget2','18/10/2015',2016,'luctus et ultrices posuere cubilia Curae; Phasellus ornare. Fusce mollis. Duis sit amet diam eu dolor egestas rhoncus. Proin nisl sem, consequat nec, mollis vitae, posuere at, velit. Cras lorem lorem, luctus ut, pellentesque eget, dictum placerat, augue. Sed molestie. Sed id risus quis diam luctus lobortis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Mauris ut quam vel sapien imperdiet ornare. In faucibus. Morbi vehicula. Pellentesque tincidunt tempus risus. Donec');

--Request
INSERT INTO Request(studentCode,adminCode,newCourse_Code,approved,reasonForChange) VALUES ( 34,76,2,TRUE,'Qorem ipsum dohor sit emet, consectetur Jdipiscing ecit. Etidm pWoreet aeo mi, eu congue nuxcs dJpibus non. Nunc hendrerit suscipit edementum. AeneOn dignissim convkvnis vudputNte. PhBsecwus dHpibus congue bibero id hendrerit.');
INSERT INTO Request(studentCode,adminCode,newCourse_Code,approved,reasonForChange) VALUES (  56,41,2,FALSE,'Korem ipsum doqor sit emet, consectetur Fdipiscing euit. Etifm tRoreet ieo mi, eu congue nuvdd dKpibus non. Nunc hendrerit suscipit emementum. Aenenn dignissim convMzlis vuoputute. Phjsevsus dmpibus congue hibero id hendrerit.');
INSERT INTO Request(studentCode,adminCode,newCourse_Code,approved,reasonForChange) VALUES ( 89,46,2,TRUE,'Porem ipsum doqor sit Amet, consectetur kdipiscing evit. Etixm cxoreet leo mi, eu congue nubvL dgpibus non. Nunc hendrerit suscipit ehementum. AeneNn dignissim convTslis vuqputyte. Phusepkus dtpibus congue tibero id hendrerit.');
INSERT INTO Request(studentCode,adminCode,newCourse_Code,approved,reasonForChange) VALUES ( 1,52,2,TRUE,'Qorem ipsum dosor sit Omet, consectetur Tdipiscing evit. Etiim zPoreet feo mi, eu congue nuwco dfpibus non. Nunc hendrerit suscipit egementum. Aenewn dignissim convxzpis vuaputOte. PhTseyeus dapibus congue nibero id hendrerit.');
INSERT INTO Request(studentCode,adminCode,newCourse_Code,approved,reasonForChange) VALUES ( 68,98,2,FALSE,'Dorem ipsum doxor sit Lmet, consectetur ddipiscing eqit. Etikm hyoreet yeo mi, eu congue nujgZ dApibus non. Nunc hendrerit suscipit evementum. AeneZn dignissim convGhcis vutputkte. Phnsedsus dKpibus congue jibero id hendrerit.');
INSERT INTO Request(studentCode,adminCode,newCourse_Code,approved,reasonForChange) VALUES ( 18,9,2,TRUE,'Norem ipsum dodor sit omet, consectetur Adipiscing esit. Etigm iooreet geo mi, eu congue nuxiu dZpibus non. Nunc hendrerit suscipit ewementum. AenePn dignissim convkvvis vumputGte. Phxseqfus dHpibus congue hibero id hendrerit.');
INSERT INTO Request(studentCode,adminCode,newCourse_Code,approved,reasonForChange) VALUES ( 83,96,2,TRUE,'Sorem ipsum dojor sit wmet, consectetur vdipiscing ehit. Etiam aForeet meo mi, eu congue numjI dvpibus non. Nunc hendrerit suscipit egementum. Aenedn dignissim convLjiis vupputate. Phdseavus dHpibus congue eibero id hendrerit.');
INSERT INTO Request(studentCode,adminCode,newCourse_Code,approved,reasonForChange) VALUES ( 71,96,2,TRUE,'Xorem ipsum doeor sit Fmet, consectetur Pdipiscing ehit. EtiHm iHoreet seo mi, eu congue nuomU dtpibus non. Nunc hendrerit suscipit ejementum. AeneHn dignissim convBjmis vuwputxte. Phdsesous dqpibus congue libero id hendrerit.');
INSERT INTO Request(studentCode,adminCode,newCourse_Code,approved,reasonForChange) VALUES ( 95,6,2,TRUE,'Eorem ipsum dobor sit kmet, consectetur Mdipiscing egit. Etivm ujoreet geo mi, eu congue nuouG dppibus non. Nunc hendrerit suscipit exementum. Aenetn dignissim convSveis vujputBte. PhIsetmus dWpibus congue nibero id hendrerit.');
INSERT INTO Request(studentCode,adminCode,newCourse_Code,approved,reasonForChange) VALUES (40,2,2,TRUE,'Rorem ipsum dohor sit amet, consectetur Jdipiscing eyit. Etikm bToreet qeo mi, eu congue nuoes dSpibus non. Nunc hendrerit suscipit esementum. AeneSn dignissim convUqeis vuuputLte. Phxseufus dUpibus congue pibero id hendrerit.');
INSERT INTO Request(studentCode,adminCode,newCourse_Code,approved,reasonForChange) VALUES (96,56,2,FALSE,'Qorem ipsum donor sit Hmet, consectetur hdipiscing eeit. Etixm sUoreet weo mi, eu congue nutfb dXpibus non. Nunc hendrerit suscipit eoementum. Aenean dignissim convaeqis vutputSte. Phgsezcus dYpibus congue gibero id hendrerit.');
INSERT INTO Request(studentCode,adminCode,newCourse_Code,approved,reasonForChange) VALUES (29,31,2,FALSE,'Porem ipsum domor sit tmet, consectetur qdipiscing esit. Etivm mDoreet ceo mi, eu congue nuxdd dEpibus non. Nunc hendrerit suscipit esementum. AeneXn dignissim convihnis vugputRte. Phnseemus dopibus congue gibero id hendrerit.');
INSERT INTO Request(studentCode,adminCode,newCourse_Code,approved,reasonForChange) VALUES (83,76,2,TRUE,'Sorem ipsum doaor sit Vmet, consectetur Adipiscing eeit. EtiIm eForeet meo mi, eu congue nuokm dypibus non. Nunc hendrerit suscipit erementum. AeneOn dignissim convYavis vuqputVte. Phuseezus dhpibus congue kibero id hendrerit.');
INSERT INTO Request(studentCode,adminCode,newCourse_Code,approved,reasonForChange) VALUES (38,20,2,TRUE,'Zorem ipsum dohor sit Kmet, consectetur Mdipiscing ebit. Etiim fdoreet reo mi, eu congue nuxxK dcpibus non. Nunc hendrerit suscipit ekementum. AeneSn dignissim convjajis vuoputGte. PhQsexlus dZpibus congue vibero id hendrerit.');
INSERT INTO Request(studentCode,adminCode,newCourse_Code,approved,reasonForChange) VALUES (52,15,2,TRUE,'Torem ipsum doeor sit hmet, consectetur rdipiscing ehit. EtiTm bjoreet jeo mi, eu congue nuyke dApibus non. Nunc hendrerit suscipit ekementum. Aenern dignissim convjskis vufputLte. PhEseenus dmpibus congue nibero id hendrerit.');
INSERT INTO Request(studentCode,adminCode,newCourse_Code,approved,reasonForChange) VALUES (73,62,2,FALSE,'Norem ipsum doaor sit Kmet, consectetur vdipiscing edit. Etiom nLoreet teo mi, eu congue nulak dSpibus non. Nunc hendrerit suscipit eqementum. Aenemn dignissim convYbais vufputdte. Phvseumus dLpibus congue pibero id hendrerit.');
INSERT INTO Request(studentCode,adminCode,newCourse_Code,approved,reasonForChange) VALUES (46,17,2,FALSE,'Corem ipsum doyor sit bmet, consectetur Jdipiscing ebit. Etiim jPoreet leo mi, eu congue nueid dNpibus non. Nunc hendrerit suscipit evementum. Aenesn dignissim convCcfis vurputpte. Phcsekkus ddpibus congue libero id hendrerit.');
INSERT INTO Request(studentCode,adminCode,newCourse_Code,approved,reasonForChange) VALUES (100,79,2,TRUE,'Oorem ipsum docor sit imet, consectetur Edipiscing eeit. Etiqm dsoreet ieo mi, eu congue nujaX dTpibus non. Nunc hendrerit suscipit edementum. Aenefn dignissim convTslis vuvputWte. PhIseqrus dvpibus congue yibero id hendrerit.');
INSERT INTO Request(studentCode,adminCode,newCourse_Code,approved,reasonForChange) VALUES (44,70,2,FALSE,'Forem ipsum dodor sit qmet, consectetur fdipiscing euit. Etiem aZoreet aeo mi, eu congue nuhyQ dvpibus non. Nunc hendrerit suscipit ebementum. AeneGn dignissim convdlxis vuyputvte. Phpsemtus dspibus congue nibero id hendrerit.');
INSERT INTO Request(studentCode,adminCode,newCourse_Code,approved,reasonForChange) VALUES (93,20,2,FALSE,'Xorem ipsum douor sit ymet, consectetur ldipiscing ejit. EtiLm anoreet xeo mi, eu congue nuomi dgpibus non. Nunc hendrerit suscipit edementum. Aenekn dignissim convebiis vubputIte. PhTsecbus dipibus congue eibero id hendrerit.');
INSERT INTO Request(studentCode,adminCode,newCourse_Code,approved,reasonForChange) VALUES (47,21,2,TRUE,'Torem ipsum doxor sit bmet, consectetur idipiscing edit. Etium iAoreet oeo mi, eu congue nusdU dfpibus non. Nunc hendrerit suscipit epementum. Aenefn dignissim convElais vurputite. Physekyus dApibus congue kibero id hendrerit.');
INSERT INTO Request(studentCode,adminCode,newCourse_Code,approved,reasonForChange) VALUES (67,77,2,TRUE,'Lorem ipsum dozor sit kmet, consectetur gdipiscing edit. Etiim cToreet peo mi, eu congue numzu dbpibus non. Nunc hendrerit suscipit epementum. AeneYn dignissim convnlwis vutputmte. Phtsenpus dHpibus congue zibero id hendrerit.');
INSERT INTO Request(studentCode,adminCode,newCourse_Code,approved,reasonForChange) VALUES (45,42,2,TRUE,'Eorem ipsum dovor sit amet, consectetur Wdipiscing erit. EtiQm rCoreet aeo mi, eu congue nuqhK dVpibus non. Nunc hendrerit suscipit esementum. AeneXn dignissim convqldis vutputqte. Phrsedrus dOpibus congue bibero id hendrerit.');
INSERT INTO Request(studentCode,adminCode,newCourse_Code,approved,reasonForChange) VALUES (56,38,2,TRUE,'Aorem ipsum doaor sit qmet, consectetur ydipiscing elit. EtiEm bRoreet yeo mi, eu congue nuaqf dspibus non. Nunc hendrerit suscipit ezementum. AeneIn dignissim convnvgis vutputLte. Phasekcus dOpibus congue ribero id hendrerit.');
INSERT INTO Request(studentCode,adminCode,newCourse_Code,approved,reasonForChange) VALUES (96,67,2,TRUE,'Morem ipsum dowor sit Omet, consectetur Jdipiscing euit. EtiBm eeoreet weo mi, eu congue nucyu dWpibus non. Nunc hendrerit suscipit enementum. Aeneon dignissim convrdois vucputmte. PhJseajus dtpibus congue uibero id hendrerit.');
INSERT INTO Request(studentCode,adminCode,newCourse_Code,approved,reasonForChange) VALUES (82,19,2,FALSE,'Porem ipsum dopor sit lmet, consectetur Udipiscing eqit. Etivm sKoreet zeo mi, eu congue nubqo djpibus non. Nunc hendrerit suscipit ebementum. AeneUn dignissim convsrnis vucputxte. PhRseibus dRpibus congue aibero id hendrerit.');
INSERT INTO Request(studentCode,adminCode,newCourse_Code,approved,reasonForChange) VALUES (58,94,2,FALSE,'Yorem ipsum dobor sit bmet, consectetur ndipiscing eeit. Etiam pPoreet ieo mi, eu congue nugbd dBpibus non. Nunc hendrerit suscipit exementum. Aeneon dignissim convndpis vuaputhte. Phusexvus dVpibus congue ribero id hendrerit.');
INSERT INTO Request(studentCode,adminCode,newCourse_Code,approved,reasonForChange) VALUES (87,24,2,TRUE,'Porem ipsum dovor sit Emet, consectetur Ddipiscing enit. Etism xZoreet neo mi, eu congue nuliT dgpibus non. Nunc hendrerit suscipit enementum. Aeneun dignissim convNpzis vuhputTte. PhXsegmus dTpibus congue wibero id hendrerit.');
INSERT INTO Request(studentCode,adminCode,newCourse_Code,approved,reasonForChange) VALUES (21,17,2,TRUE,'Sorem ipsum dopor sit Cmet, consectetur xdipiscing euit. EtiSm dyoreet feo mi, eu congue nuihC djpibus non. Nunc hendrerit suscipit egementum. AeneNn dignissim convHrpis vuhputLte. PhHseruus dspibus congue bibero id hendrerit.');
INSERT INTO Request(studentCode,adminCode,newCourse_Code,approved,reasonForChange) VALUES (30,77,2,FALSE,'Rorem ipsum dolor sit qmet, consectetur idipiscing ebit. EtiMm eZoreet geo mi, eu congue nunvS dQpibus non. Nunc hendrerit suscipit ebementum. AeneNn dignissim convFglis vuaputHte. PhWsemlus dzpibus congue nibero id hendrerit.');
INSERT INTO Request(studentCode,adminCode,newCourse_Code,approved,reasonForChange) VALUES (15,63,2,FALSE,'Xorem ipsum doaor sit nmet, consectetur idipiscing eiit. EtiHm broreet meo mi, eu congue nuowl dHpibus non. Nunc hendrerit suscipit eqementum. AeneTn dignissim convXdois vuqputfte. Phmseaaus dHpibus congue pibero id hendrerit.');
INSERT INTO Request(studentCode,adminCode,newCourse_Code,approved,reasonForChange) VALUES (21,2,2,FALSE,'Torem ipsum dowor sit xmet, consectetur pdipiscing ewit. EtiCm veoreet aeo mi, eu congue nuvkI dlpibus non. Nunc hendrerit suscipit eaementum. AeneQn dignissim convmncis vuwputmte. PhYsermus dSpibus congue nibero id hendrerit.');

--Area
INSERT INTO Area (area) VALUES ('History');
INSERT INTO Area (area) VALUES ('Sociology');
INSERT INTO Area (area) VALUES ('Science of Earth Systems');
INSERT INTO Area (area) VALUES ('Spanish');
INSERT INTO Area (area) VALUES ('Statistical Science');
INSERT INTO Area (area) VALUES ('Civil Engineering');
INSERT INTO Area (area) VALUES ('Computer Science');
INSERT INTO Area (area) VALUES ('German Studies');
INSERT INTO Area (area) VALUES ('Religious Studies');
INSERT INTO Area (area) VALUES ('History of Art');
INSERT INTO Area (area) VALUES ('Physics');
INSERT INTO Area (area) VALUES ('Government');
INSERT INTO Area (area) VALUES ('Nutritional Sciences');
INSERT INTO Area (area) VALUES ('Near Eastern Studies');
INSERT INTO Area (area) VALUES ('Music');
INSERT INTO Area (area) VALUES ('Mechanical Engineering');
INSERT INTO Area (area) VALUES ('Performing and Media Arts');
INSERT INTO Area (area) VALUES ('Philosophy');
INSERT INTO Area (area) VALUES ('Plant Science');
INSERT INTO Area (area) VALUES ('aliquet vel, vulputate');
INSERT INTO Area (area) VALUES ('porttitor vulputate, posuere');
INSERT INTO Area (area) VALUES ('Urban and Regional Studies');
INSERT INTO Area (area) VALUES ('Viticulture and Enology');

--ROOM 
INSERT INTO Room(room) VALUES ('N602');
INSERT INTO Room(room) VALUES ('S063');
INSERT INTO Room(room) VALUES ('O683');
INSERT INTO Room(room) VALUES ('B120');
INSERT INTO Room(room) VALUES ('A096');
INSERT INTO Room(room) VALUES ('Z158');
INSERT INTO Room(room) VALUES ('N669');
INSERT INTO Room(room) VALUES ('M492');
INSERT INTO Room(room) VALUES ('D284');
INSERT INTO Room(room) VALUES ('O704');
INSERT INTO Room(room) VALUES ('T222');
INSERT INTO Room(room) VALUES ('A608');
INSERT INTO Room(room) VALUES ('N371');
INSERT INTO Room(room) VALUES ('X113');
INSERT INTO Room(room) VALUES ('S754');
INSERT INTO Room(room) VALUES ('S943');
INSERT INTO Room(room) VALUES ('K780');
INSERT INTO Room(room) VALUES ('K797');
INSERT INTO Room(room) VALUES ('W372');
INSERT INTO Room(room) VALUES ('K565');
INSERT INTO Room(room) VALUES ('S365');
INSERT INTO Room(room) VALUES ('J190');
INSERT INTO Room(room) VALUES ('X833');
INSERT INTO Room(room) VALUES ('P807');
INSERT INTO Room(room) VALUES ('X498');
INSERT INTO Room(room) VALUES ('F227');
INSERT INTO Room(room) VALUES ('W642');
INSERT INTO Room(room) VALUES ('S436');
INSERT INTO Room(room) VALUES ('L359');
INSERT INTO Room(room) VALUES ('S134');
INSERT INTO Room(room) VALUES ('I293');
INSERT INTO Room(room) VALUES ('L960');
INSERT INTO Room(room) VALUES ('N091');
INSERT INTO Room(room) VALUES ('T890');
INSERT INTO Room(room) VALUES ('G501');
INSERT INTO Room(room) VALUES ('O137');
INSERT INTO Room(room) VALUES ('Y594');
INSERT INTO Room(room) VALUES ('A337');
INSERT INTO Room(room) VALUES ('P993');
INSERT INTO Room(room) VALUES ('R828');
INSERT INTO Room(room) VALUES ('V426');
INSERT INTO Room(room) VALUES ('E924');
INSERT INTO Room(room) VALUES ('E535');
INSERT INTO Room(room) VALUES ('E625');
INSERT INTO Room(room) VALUES ('V593');
INSERT INTO Room(room) VALUES ('G506');
INSERT INTO Room(room) VALUES ('T251');
INSERT INTO Room(room) VALUES ('J670');
INSERT INTO Room(room) VALUES ('R337');
INSERT INTO Room(room) VALUES ('N414');


-- Curricular Unit
INSERT INTO CurricularUnit(name, areaID, credits) VALUES ('Programming 3',3,6);
INSERT INTO CurricularUnit(name, areaID, credits) VALUES ('Programming 5',9,6);
INSERT INTO CurricularUnit(name, areaID, credits) VALUES ('Physics 2',14,6);
INSERT INTO CurricularUnit(name, areaID, credits) VALUES ('Database 2',8,6);
INSERT INTO CurricularUnit(name, areaID, credits) VALUES ('Programming 1',14,6);
INSERT INTO CurricularUnit(name, areaID, credits) VALUES ('Physics 3',5,6);
INSERT INTO CurricularUnit(name, areaID, credits) VALUES ('Math 3',11,6);
INSERT INTO CurricularUnit(name, areaID, credits) VALUES ('Programming 9',7,6);
INSERT INTO CurricularUnit(name, areaID, credits) VALUES ('Database 3',3,6);
INSERT INTO CurricularUnit(name, areaID, credits) VALUES ('Programming 4',11,6);
INSERT INTO CurricularUnit(name, areaID, credits) VALUES ('Design 1',3,6);
INSERT INTO CurricularUnit(name, areaID, credits) VALUES ('Programming 7',4,6);
INSERT INTO CurricularUnit(name, areaID, credits) VALUES ('Programming 2',13,6);
INSERT INTO CurricularUnit(name, areaID, credits) VALUES ('Math 4',2,6);
INSERT INTO CurricularUnit(name, areaID, credits) VALUES ('Algebra 1',9,6);
INSERT INTO CurricularUnit(name, areaID, credits) VALUES ('Database 5',2,6);
INSERT INTO CurricularUnit(name, areaID, credits) VALUES ('Programming 6',1,6);
INSERT INTO CurricularUnit(name, areaID, credits) VALUES ('Database 1',1,6);
INSERT INTO CurricularUnit(name, areaID, credits) VALUES ('Algebra 2',8,6);
INSERT INTO CurricularUnit(name, areaID, credits) VALUES ('Programming 8',4,6);

 --Class
 /*
INSERT INTO Class (occurrenceID,duration,roomID,classDate,summary) VALUES (6,116,8,'06/04/2016','nibh mauris tincidunt velit');
INSERT INTO Class (occurrenceID,duration,roomID,classDate,summary) VALUES (22,89,47,'09/04/2016','rutrum ad massa rhoncus auctor quis In ultrices vel sollicitudin Proin In Nunc per');
INSERT INTO Class (occurrenceID,duration,roomID,classDate,summary) VALUES (23,65,27,'07/04/2016','primis ante semper eu erat ultrices');
INSERT INTO Class (occurrenceID,duration,roomID,classDate,summary) VALUES (18,60,26,'06/04/2016','pellentesque interdum ornare volutpat amet rhoncus congue ipsum sociosqu Class Nulla');
INSERT INTO Class (occurrenceID,duration,roomID,classDate,summary) VALUES (12,105,44,'10/04/2016','senectus dictum Integer');
INSERT INTO Class (occurrenceID,duration,roomID,classDate,summary) VALUES (15,101,31,'07/04/2016','condimentum dapibus Donec dis volutpat torquent leo arcu sit Nam');
INSERT INTO Class (occurrenceID,duration,roomID,classDate,summary) VALUES (22,98,32,'07/04/2016','magna Vestibulum blandit nostra facilisis condimentum imperdiet varius velit Sed vel Cum inceptos risus');
INSERT INTO Class (occurrenceID,duration,roomID,classDate,summary) VALUES (22,111,21,'08/04/2016','velit cursus natoque ullamcorper Integer pellentesque blandit');
INSERT INTO Class (occurrenceID,duration,roomID,classDate,summary) VALUES (8,108,49,'06/04/2016','diam Praesent Aenean nostra metus bibendum libero Praesent sit ut');
INSERT INTO Class (occurrenceID,duration,roomID,classDate,summary) VALUES (23,53,45,'10/04/2016','morbi sed lectus Nunc consectetuer laoreet');
INSERT INTO Class (occurrenceID,duration,roomID,classDate,summary) VALUES (4,49,8,'09/04/2016','sodales ultrices felis');
INSERT INTO Class (occurrenceID,duration,roomID,classDate,summary) VALUES (13,109,11,'04/04/2016','In gravida semper Aenean nostra blandit dignissim');
INSERT INTO Class (occurrenceID,duration,roomID,classDate,summary) VALUES (13,90,42,'05/04/2016','volutpat lorem tortor dictum lobortis');
INSERT INTO Class (occurrenceID,duration,roomID,classDate,summary) VALUES (7,45,39,'09/04/2016','mauris Integer Nulla id imperdiet suscipit ultrices fames bibendum urna magnis metus consectetuer nisl mollis');
INSERT INTO Class (occurrenceID,duration,roomID,classDate,summary) VALUES (11,90,10,'07/04/2016','aliquet Morbi urna varius Vestibulum Sed Praesent dui');
INSERT INTO Class (occurrenceID,duration,roomID,classDate,summary) VALUES (12,64,42,'08/04/2016','imperdiet vulputate');
INSERT INTO Class (occurrenceID,duration,roomID,classDate,summary) VALUES (1,68,37,'10/04/2016','sollicitudin Nulla congue augue eu Lorem Class condimentum pretium varius ligula habitant Etiam Vivamus morbi');
INSERT INTO Class (occurrenceID,duration,roomID,classDate,summary) VALUES (19,81,40,'08/04/2016','nonummy nascetur sit Curae primis natoque eleifend tincidunt');
INSERT INTO Class (occurrenceID,duration,roomID,classDate,summary) VALUES (0,118,40,'07/04/2016','imperdiet Ut quam libero Lorem suscipit orci hendrerit suscipit posuere nonummy dui');
INSERT INTO Class (occurrenceID,duration,roomID,classDate,summary) VALUES (20,88,18,'08/04/2016','mauris tempor nostra Nulla');
INSERT INTO Class (occurrenceID,duration,roomID,classDate,summary) VALUES (5,80,3,'10/04/2016','vestibulum ultrices sem erat sagittis dui porttitor consequat Morbi ligula condimentum Cras sociis mauris sodales');
INSERT INTO Class (occurrenceID,duration,roomID,classDate,summary) VALUES (9,103,20,'10/04/2016','quis euismod eu nonummy convallis nulla molestie');
INSERT INTO Class (occurrenceID,duration,roomID,classDate,summary) VALUES (11,78,11,'05/04/2016','elit ac laoreet est Phasellus litora libero');
INSERT INTO Class (occurrenceID,duration,roomID,classDate,summary) VALUES (5,60,28,'06/04/2016','laoreet eros montes elementum sociis parturient nascetur netus');
INSERT INTO Class (occurrenceID,duration,roomID,classDate,summary) VALUES (19,105,1,'05/04/2016','dignissim velit ut massa');
INSERT INTO Class (occurrenceID,duration,roomID,classDate,summary) VALUES (5,118,38,'10/04/2016','sociosqu parturient Aliquam taciti Sed urna Praesent non');
INSERT INTO Class (occurrenceID,duration,roomID,classDate,summary) VALUES (3,96,15,'06/04/2016','sociis eleifend vel fames Nam');
INSERT INTO Class (occurrenceID,duration,roomID,classDate,summary) VALUES (0,101,9,'06/04/2016','sem Nunc Fusce consequat amet facilisi augue Ut at');
INSERT INTO Class (occurrenceID,duration,roomID,classDate,summary) VALUES (20,47,35,'05/04/2016','Nam In ridiculus urna massa tempus enim ac taciti feugiat Fusce fames inceptos');
INSERT INTO Class (occurrenceID,duration,roomID,classDate,summary) VALUES (2,45,45,'09/04/2016','imperdiet lacinia In placerat quis');
INSERT INTO Class (occurrenceID,duration,roomID,classDate,summary) VALUES (16,112,43,'06/04/2016','In ad Aliquam nunc est placerat elementum nascetur nulla senectus fames sit accumsan');
INSERT INTO Class (occurrenceID,duration,roomID,classDate,summary) VALUES (21,53,36,'07/04/2016','quam malesuada ad Duis morbi volutpat aptent accumsan hymenaeos');
INSERT INTO Class (occurrenceID,duration,roomID,classDate,summary) VALUES (17,80,10,'04/04/2016','odio velit Cum posuere vel sollicitudin mollis lorem Pellentesque Nullam Integer Nulla non sociosqu');
INSERT INTO Class (occurrenceID,duration,roomID,classDate,summary) VALUES (17,81,49,'09/04/2016','vitae magnis ornare at massa et');
INSERT INTO Class (occurrenceID,duration,roomID,classDate,summary) VALUES (6,105,15,'04/04/2016','quam nec semper lectus mi tortor sapien Ut inceptos blandit conubia lobortis Pellentesque ultricies');
INSERT INTO Class (occurrenceID,duration,roomID,classDate,summary) VALUES (2,107,33,'07/04/2016','nascetur natoque Curabitur per Quisque sit sem lacinia per In');
INSERT INTO Class (occurrenceID,duration,roomID,classDate,summary) VALUES (8,62,38,'05/04/2016','leo mus venenatis vel pellentesque accumsan commodo');
INSERT INTO Class (occurrenceID,duration,roomID,classDate,summary) VALUES (4,60,36,'05/04/2016','taciti vehicula');
INSERT INTO Class (occurrenceID,duration,roomID,classDate,summary) VALUES (6,64,24,'06/04/2016','consequat sem');
INSERT INTO Class (occurrenceID,duration,roomID,classDate,summary) VALUES (25,86,10,'09/04/2016','dui iaculis Mauris Ut bibendum non elit iaculis');
INSERT INTO Class (occurrenceID,duration,roomID,classDate,summary) VALUES (16,88,1,'09/04/2016','pretium leo sodales a viverra mus cursus placerat egestas rhoncus');
INSERT INTO Class (occurrenceID,duration,roomID,classDate,summary) VALUES (14,89,1,'09/04/2016','velit ultricies magnis adipiscing nisi dictum facilisis ac eleifend Integer');
INSERT INTO Class (occurrenceID,duration,roomID,classDate,summary) VALUES (14,50,24,'05/04/2016','nunc sit Nullam');
INSERT INTO Class (occurrenceID,duration,roomID,classDate,summary) VALUES (19,119,25,'05/04/2016','ridiculus libero sem');
INSERT INTO Class (occurrenceID,duration,roomID,classDate,summary) VALUES (10,62,1,'07/04/2016','est nisi condimentum imperdiet felis placerat Cum sit massa litora');
INSERT INTO Class (occurrenceID,duration,roomID,classDate,summary) VALUES (16,62,9,'10/04/2016','lacus eleifend elit Ut');
INSERT INTO Class (occurrenceID,duration,roomID,classDate,summary) VALUES (10,80,50,'08/04/2016','magnis');
INSERT INTO Class (occurrenceID,duration,roomID,classDate,summary) VALUES (4,96,37,'10/04/2016','Morbi pretium');
INSERT INTO Class (occurrenceID,duration,roomID,classDate,summary) VALUES (3,108,26,'05/04/2016','sem laoreet gravida Maecenas magna fringilla Curae quam dui netus eget dolor fringilla');
INSERT INTO Class (occurrenceID,duration,roomID,classDate,summary) VALUES (10,96,18,'09/04/2016','in consequat natoque sed');

--Attendance
INSERT INTO Attendance (studentCode,classID,attended) VALUES (35,43,FALSE);
INSERT INTO Attendance (studentCode,classID,attended) VALUES (26,13,FALSE);
INSERT INTO Attendance (studentCode,classID,attended) VALUES (38,25,FALSE);
INSERT INTO Attendance (studentCode,classID,attended) VALUES (44,28,FALSE);
INSERT INTO Attendance (studentCode,classID,attended) VALUES (37,21,TRUE);
INSERT INTO Attendance (studentCode,classID,attended) VALUES (43,41,FALSE);
INSERT INTO Attendance (studentCode,classID,attended) VALUES (8,9,FALSE);
INSERT INTO Attendance (studentCode,classID,attended) VALUES (1,21,TRUE);
INSERT INTO Attendance (studentCode,classID,attended) VALUES (39,19,TRUE);
INSERT INTO Attendance (studentCode,classID,attended) VALUES (32,47,FALSE);
INSERT INTO Attendance (studentCode,classID,attended) VALUES (32,48,TRUE);
INSERT INTO Attendance (studentCode,classID,attended) VALUES (37,24,FALSE);
INSERT INTO Attendance (studentCode,classID,attended) VALUES (15,8,TRUE);
INSERT INTO Attendance (studentCode,classID,attended) VALUES (13,39,FALSE);
INSERT INTO Attendance (studentCode,classID,attended) VALUES (49,34,TRUE);
INSERT INTO Attendance (studentCode,classID,attended) VALUES (1,23,TRUE);
INSERT INTO Attendance (studentCode,classID,attended) VALUES (39,22,TRUE);
INSERT INTO Attendance (studentCode,classID,attended) VALUES (8,47,TRUE);
INSERT INTO Attendance (studentCode,classID,attended) VALUES (17,43,FALSE);
INSERT INTO Attendance (studentCode,classID,attended) VALUES (26,34,TRUE);
INSERT INTO Attendance (studentCode,classID,attended) VALUES (38,38,FALSE);
INSERT INTO Attendance (studentCode,classID,attended) VALUES (35,18,TRUE);
INSERT INTO Attendance (studentCode,classID,attended) VALUES (18,32,TRUE);
INSERT INTO Attendance (studentCode,classID,attended) VALUES (7,7,TRUE);
INSERT INTO Attendance (studentCode,classID,attended) VALUES (6,44,FALSE);
INSERT INTO Attendance (studentCode,classID,attended) VALUES (16,23,TRUE);
INSERT INTO Attendance (studentCode,classID,attended) VALUES (12,30,TRUE);
INSERT INTO Attendance (studentCode,classID,attended) VALUES (21,43,FALSE);
INSERT INTO Attendance (studentCode,classID,attended) VALUES (5,27,TRUE);
INSERT INTO Attendance (studentCode,classID,attended) VALUES (30,24,TRUE);
INSERT INTO Attendance (studentCode,classID,attended) VALUES (37,15,TRUE);
INSERT INTO Attendance (studentCode,classID,attended) VALUES (48,31,FALSE);
INSERT INTO Attendance (studentCode,classID,attended) VALUES (25,3,FALSE);
INSERT INTO Attendance (studentCode,classID,attended) VALUES (39,36,TRUE);
INSERT INTO Attendance (studentCode,classID,attended) VALUES (8,30,TRUE);
INSERT INTO Attendance (studentCode,classID,attended) VALUES (5,10,FALSE);
INSERT INTO Attendance (studentCode,classID,attended) VALUES (10,44,FALSE);
INSERT INTO Attendance (studentCode,classID,attended) VALUES (13,28,FALSE);
INSERT INTO Attendance (studentCode,classID,attended) VALUES (36,8,TRUE);
INSERT INTO Attendance (studentCode,classID,attended) VALUES (19,38,TRUE);
INSERT INTO Attendance (studentCode,classID,attended) VALUES (40,29,FALSE);
INSERT INTO Attendance (studentCode,classID,attended) VALUES (4,4,TRUE);
INSERT INTO Attendance (studentCode,classID,attended) VALUES (29,20,FALSE);
INSERT INTO Attendance (studentCode,classID,attended) VALUES (48,4,FALSE);
INSERT INTO Attendance (studentCode,classID,attended) VALUES (27,42,FALSE);
INSERT INTO Attendance (studentCode,classID,attended) VALUES (3,36,TRUE);
INSERT INTO Attendance (studentCode,classID,attended) VALUES (50,24,TRUE);
INSERT INTO Attendance (studentCode,classID,attended) VALUES (43,36,FALSE);
INSERT INTO Attendance (studentCode,classID,attended) VALUES (32,6,TRUE);
INSERT INTO Attendance (studentCode,classID,attended) VALUES (1,4,TRUE);

--Evaluation
INSERT INTO Evaluation (weight,cuOccurrenceID,evaluationDate) VALUES (3,20,'05/04/2016');
INSERT INTO Evaluation (weight,cuOccurrenceID,evaluationDate) VALUES (53,40,'24/05/2016');
INSERT INTO Evaluation (weight,cuOccurrenceID,evaluationDate) VALUES (96,16,'20/05/2016');
INSERT INTO Evaluation (weight,cuOccurrenceID,evaluationDate) VALUES (32,47,'01/06/2016');
INSERT INTO Evaluation (weight,cuOccurrenceID,evaluationDate) VALUES (55,31,'23/06/2016');
INSERT INTO Evaluation (weight,cuOccurrenceID,evaluationDate) VALUES (9,13,'26/01/2016');
INSERT INTO Evaluation (weight,cuOccurrenceID,evaluationDate) VALUES (21,11,'17/05/2016');
INSERT INTO Evaluation (weight,cuOccurrenceID,evaluationDate) VALUES (28,50,'01/03/2016');
INSERT INTO Evaluation (weight,cuOccurrenceID,evaluationDate) VALUES (39,32,'02/06/2016');
INSERT INTO Evaluation (weight,cuOccurrenceID,evaluationDate) VALUES (23,20,'08/05/2016');
INSERT INTO Evaluation (weight,cuOccurrenceID,evaluationDate) VALUES (83,20,'21/05/2016');
INSERT INTO Evaluation (weight,cuOccurrenceID,evaluationDate) VALUES (6,16,'30/03/2016');
INSERT INTO Evaluation (weight,cuOccurrenceID,evaluationDate) VALUES (64,38,'03/01/2016');
INSERT INTO Evaluation (weight,cuOccurrenceID,evaluationDate) VALUES (84,10,'25/06/2016');
INSERT INTO Evaluation (weight,cuOccurrenceID,evaluationDate) VALUES (81,37,'04/04/2016');
INSERT INTO Evaluation (weight,cuOccurrenceID,evaluationDate) VALUES (56,39,'07/01/2016');
INSERT INTO Evaluation (weight,cuOccurrenceID,evaluationDate) VALUES (89,4,'26/01/2016');
INSERT INTO Evaluation (weight,cuOccurrenceID,evaluationDate) VALUES (29,22,'26/05/2016');
INSERT INTO Evaluation (weight,cuOccurrenceID,evaluationDate) VALUES (58,17,'16/05/2016');
INSERT INTO Evaluation (weight,cuOccurrenceID,evaluationDate) VALUES (40,37,'01/03/2016');
INSERT INTO Evaluation (weight,cuOccurrenceID,evaluationDate) VALUES (14,1,'25/03/2016');
INSERT INTO Evaluation (weight,cuOccurrenceID,evaluationDate) VALUES (79,6,'16/02/2016');
INSERT INTO Evaluation (weight,cuOccurrenceID,evaluationDate) VALUES (72,4,'09/03/2016');
INSERT INTO Evaluation (weight,cuOccurrenceID,evaluationDate) VALUES (29,9,'07/04/2016');
INSERT INTO Evaluation (weight,cuOccurrenceID,evaluationDate) VALUES (37,18,'07/04/2016');
INSERT INTO Evaluation (weight,cuOccurrenceID,evaluationDate) VALUES (26,21,'18/05/2016');
INSERT INTO Evaluation (weight,cuOccurrenceID,evaluationDate) VALUES (91,8,'14/01/2016');
INSERT INTO Evaluation (weight,cuOccurrenceID,evaluationDate) VALUES (87,14,'01/03/2016');
INSERT INTO Evaluation (weight,cuOccurrenceID,evaluationDate) VALUES (65,1,'19/02/2016');
INSERT INTO Evaluation (weight,cuOccurrenceID,evaluationDate) VALUES (100,14,'03/04/2016');
INSERT INTO Evaluation (weight,cuOccurrenceID,evaluationDate) VALUES (27,20,'25/01/2016');
INSERT INTO Evaluation (weight,cuOccurrenceID,evaluationDate) VALUES (7,12,'07/01/2016');
INSERT INTO Evaluation (weight,cuOccurrenceID,evaluationDate) VALUES (73,6,'28/02/2016');
INSERT INTO Evaluation (weight,cuOccurrenceID,evaluationDate) VALUES (16,23,'18/03/2016');
INSERT INTO Evaluation (weight,cuOccurrenceID,evaluationDate) VALUES (72,1,'21/01/2016');
INSERT INTO Evaluation (weight,cuOccurrenceID,evaluationDate) VALUES (45,26,'27/01/2016');
INSERT INTO Evaluation (weight,cuOccurrenceID,evaluationDate) VALUES (35,8,'10/04/2016');
INSERT INTO Evaluation (weight,cuOccurrenceID,evaluationDate) VALUES (85,36,'28/01/2016');
INSERT INTO Evaluation (weight,cuOccurrenceID,evaluationDate) VALUES (72,32,'08/04/2016');
INSERT INTO Evaluation (weight,cuOccurrenceID,evaluationDate) VALUES (67,33,'30/04/2016');
INSERT INTO Evaluation (weight,cuOccurrenceID,evaluationDate) VALUES (28,34,'25/01/2016');
INSERT INTO Evaluation (weight,cuOccurrenceID,evaluationDate) VALUES (40,35,'07/06/2016');
INSERT INTO Evaluation (weight,cuOccurrenceID,evaluationDate) VALUES (3,18,'28/05/2016');
INSERT INTO Evaluation (weight,cuOccurrenceID,evaluationDate) VALUES (60,38,'06/03/2016');
INSERT INTO Evaluation (weight,cuOccurrenceID,evaluationDate) VALUES (25,42,'15/02/2016');
INSERT INTO Evaluation (weight,cuOccurrenceID,evaluationDate) VALUES (77,1,'08/04/2016');
INSERT INTO Evaluation (weight,cuOccurrenceID,evaluationDate) VALUES (73,14,'28/05/2016');
INSERT INTO Evaluation (weight,cuOccurrenceID,evaluationDate) VALUES (83,44,'15/04/2016');
INSERT INTO Evaluation (weight,cuOccurrenceID,evaluationDate) VALUES (33,42,'13/03/2016');
INSERT INTO Evaluation (weight,cuOccurrenceID,evaluationDate) VALUES (10,29,'04/02/2016');*/
