-- Curricular Unit
INSERT INTO CurricularUnit(name,areaID,credits) VALUES ('Corporate Law and Law of Contracts',18,6);
INSERT INTO CurricularUnit(name,areaID,credits) VALUES ('Introduction to Accounting',18,6);
INSERT INTO CurricularUnit(name,areaID,credits) VALUES ('Electromagnetism',10,6);
INSERT INTO CurricularUnit(name,areaID,credits) VALUES ('Database Management',6,6);
INSERT INTO CurricularUnit(name,areaID,credits) VALUES ('Programming Fundaments',6,6);
INSERT INTO CurricularUnit(name,areaID,credits) VALUES ('Thermal Physics',10,6);
INSERT INTO CurricularUnit(name,areaID,credits) VALUES ('Calculus',21,6);
INSERT INTO CurricularUnit(name,areaID,credits) VALUES ('Algebra',21,6);
INSERT INTO CurricularUnit(name,areaID,credits) VALUES ('Geometry',21,6);
INSERT INTO CurricularUnit(name,areaID,credits) VALUES ('Artificial intelligence',6,6);
INSERT INTO CurricularUnit(name,areaID,credits) VALUES ('Computer graphics',6,6);
INSERT INTO CurricularUnit(name,areaID,credits) VALUES ('Basic Ear Training 1',14,6);
INSERT INTO CurricularUnit(name,areaID,credits) VALUES ('World War II',9,6);
INSERT INTO CurricularUnit(name,areaID,credits) VALUES ('Sociology of Education',17,6);
INSERT INTO CurricularUnit(name,areaID,credits) VALUES ('Networking',10,6);
INSERT INTO CurricularUnit(name,areaID,credits) VALUES ('Logic',21,6);
INSERT INTO CurricularUnit(name,areaID,credits) VALUES ('Expressions and Group Dynamics',17,6);
INSERT INTO CurricularUnit(name,areaID,credits) VALUES ('Web Development',10,6);
INSERT INTO CurricularUnit(name,areaID,credits) VALUES ('Computer Vision',10,6);
INSERT INTO CurricularUnit(name,areaID,credits) VALUES ('Territorial Planning',5,6);
INSERT INTO CurricularUnit(name,areaID,credits) VALUES ('Geostatistics',4,6);